# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XWSqliteDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'ReactiveObjC'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'

  target 'XWSqliteDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XWSqliteDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


